# Generated by Django 5.2.13 on 2026-04-10 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_options_alter_category_options_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowrecord',
            options={'verbose_name': 'Phiếu mượn', 'verbose_name_plural': '2. Xét duyệt Phiếu Mượn'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Hoá đơn xuất', 'verbose_name_plural': '1. Quản lý Hoá Đơn Bán'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Chi tiết mục', 'verbose_name_plural': 'Chi tiết mục'},
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='catalog.book', verbose_name='Sách mượn'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày làm đơn'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateField(verbose_name='Hẹn ngày trả'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Đang đợi Phê Duyệt'), ('Approved', 'Đang mượn (Thủ thư đã duyệt)'), ('Returned', 'Khách đã trả (Hoàn tất)'), ('Overdue', 'Quá hạn')], default='Pending', max_length=20, verbose_name='Trạng thái hệ thống'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to=settings.AUTH_USER_MODEL, verbose_name='Sinh viên/Giáo viên'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Giao dịch lúc'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ xử lý thanh toán'), ('Paid', 'Đã thanh toán (Thành công)')], default='Pending', max_length=20, verbose_name='Thực trạng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tổng hóa đơn'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Người mua'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='catalog.book', verbose_name='Cuốn sách'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.order', verbose_name='Mã Hóa Đơn'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_time_of_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá thu'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='SL Mua'),
        ),
    ]
