# Generated by Django 5.2.13 on 2026-04-10 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Đầu sách', 'verbose_name_plural': '2. Kho Đầu sách'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': '1. Nhóm thẻ loại'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrow_stock',
            field=models.PositiveIntegerField(default=0, help_text='Số lượng tồn kho để cho mượn', verbose_name='Kho Mượn'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.category', verbose_name='Thuộc danh mục'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Upload Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Giới thiệu nội dung'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá niêm yết (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sell_stock',
            field=models.PositiveIntegerField(default=0, help_text='Số lượng tồn kho để bán', verbose_name='Kho Bán'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tựa sách'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên Thể Loại'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Đường dẫn tĩnh (Slug)'),
        ),
    ]
